#!/bin/sh

# This shell script automates getting the required build tools (apt install)

# set the shell environment variable 'UNATTENDED' to '--assume-yes' for 
# unattended use (for example in the .travis.yml script)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING Build Tools (using APT)"
echo "  (UNATTENDED: [$UNATTENDED])"
echo "-------------------------------------------------------------------"
echo ""

set -ev

apt-get update
apt-get $UNATTENDED install \
  sudo                           \
  wget                           \
  git                            \
  pkg-config                     \
  ruby                           \
  autoconf                       \
  libtool                        \
  cmake                          \
  make                           \
  gcc-9                          \
  g++-9                          \
  dpkg                           \
  dpkg-dev                       \
  gettext                        \
  openjdk-8-jre-headless         \
  libopenjp2-7-dev               \
  jq

update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90 --slave /usr/bin/g++ g++ /usr/bin/g++-12
